In [ ]:
#PYTHON LIBRARIES :
#1)NUMPY -> IT IS NUMERICAL PYTHON AND IN THE CODE WE WILL USE THE NUMPY AS NP (IS : IDENTITY OPERATOR)


In [7]:
a = 10
b = 10
a is b #CHECKS IF TWO VARIABLES POINT TO SAME LOCATION OR NOT

True

In [8]:
a = [1,2,3]
b = [2,3,1]
a is b

False

In [12]:
#(IN : MEMBERSHIP OPERATOR)
a = 5
b = [1,2,3,4,5]
print(a in b)
print(a not in b)

True
False


In [ ]:
#NUMPY LIBRARY :

In [13]:
import numpy as np

In [18]:
A = np.array([[1,2,3],[1,2,3]])
print(A)

[[1 2 3]
 [1 2 3]]


In [19]:
A.shape

(2, 3)

In [20]:
A.size

6

In [21]:
#ANONYMOUS FUNCTION :LAMBDA FUCNTION (LESS SPACE OR MORE SPACE ?)

In [22]:
#NUMPY IS USED FOR VIDEOS OR IMAGES WHEN MORE THEN 2D SIZE.

In [24]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a%b)
print(a//b)
print(a**b)

[3 5 7]
[-1 -1 -1]
[0.5        0.66666667 0.75      ]
[ 2  6 12]
[1 2 3]
[0 0 0]
[ 1  8 81]


In [29]:
#TO REDUCE ARRAY SHAPE TO 1D
p = np.array([[1,2,3],[4,5,6]])
print(p)
print(p.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [35]:
#MIN AND MAX ELEMENT OF ARRAY
a = np.array([1,2,3])
print(a.min())
print(a.max())

1
3


In [62]:
from scipy.stats import mode

In [65]:
print(a.mean())
print(np.median(a))
print(stats.mode(a))

2.0
2.0
ModeResult(mode=np.int64(1), count=np.int64(1))


In [73]:
#dot product , transpose , inverse 
#MATRIX AND PROBABILITY AND STATISTICS

a = np.array([[1,2,3],[2,3,4]])
b = np.array([[2,3,1],[9,8,7]])
print(a.dot(b.T))

[[11 46]
 [17 70]]
